'use client';
import {useState,useRef,useMemo} from 'react';
import {Search,ArrowUpRight,Play,Eye,Heart,MessageCircle,Globe2,SlidersHorizontal,ArrowRight,Layers3,Loader2,Info,X} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Skeleton} from '@/components/ui/skeleton';
import {Video,platforms,sortVideos,filterVideos,youtubeId} from '@/lib/videos';
import cookieData from '@/data/cookies.json';
import type {SourceStatus} from '@/lib/discovery';
const collection:Video[]=cookieData;
const fmt=(n:number|null)=>n===null?'—':new Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(n);
const options=[['views:desc','Most viewed'],['views:asc','Least viewed'],['likes:desc','Most liked'],['likes:asc','Least liked'],['comments:desc','Most commented'],['comments:asc','Least commented'],['published:desc','Newest first'],['published:asc','Oldest first'],['relevance:desc','Relevance']];
const marks:Record<string,string>={YouTube:'▶',Instagram:'◎',TikTok:'♪',Facebook:'f',Reddit:'r',Dailymotion:'d',Vimeo:'v',Other:'↗'};
function Picker({value,onChange,items,label}:{value:string;onChange:(v:string)=>void;items:string[][];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="picker"><SelectValue/></SelectTrigger><SelectContent>{items.map(([v,t])=><SelectItem key={v} value={v}>{t}</SelectItem>)}</SelectContent></Select>}
function duration(v:string|null){if(!v)return null;if(!v.startsWith('PT'))return v;const m=v.match(/PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?/);return m?[m[1],m[2]||'0',(m[3]||'0').padStart(2,'0')].filter(x=>x!==undefined).join(':'):null}
export default function Home(){
const [input,setInput]=useState('cookies'),[query,setQuery]=useState(''),[videos,setVideos]=useState<Video[]>([]),[collected,setCollected]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[platform,setPlatform]=useState('All platforms'),[sort,setSort]=useState('views:desc'),[date,setDate]=useState('all'),[statsOnly,setStatsOnly]=useState('all'),[selected,setSelected]=useState<Video|null>(null),[nextYoutube,setNextYoutube]=useState<string|null>(null),[elapsed,setElapsed]=useState(0),[fetched,setFetched]=useState(''),[sourceStates,setSourceStates]=useState<SourceStatus[]>([]);
const controller=useRef<AbortController|null>(null);const retrievalSort=useRef('views:desc');
function searchCollection(q=input){controller.current?.abort();setLoading(false);setError('');setCollected(true);setSourceStates([]);setFetched('');setInput(q);setQuery(q||'cookies');const words=q.toLowerCase().replace(/cookies/g,'cookie').split(/\s+/).filter(Boolean);setVideos(collection.filter(v=>words.every(w=>(v.title+' '+v.platform+' cookie').toLowerCase().replace(/cookies/g,'cookie').includes(w))));}
async function search(q=input,append=false,source=platform){q=q.trim();if(!q)return;controller.current?.abort();const ac=new AbortController();controller.current=ac;setLoading(true);setError('');const start=performance.now();if(!append){setDate('all');setStatsOnly('all');}const requested=append?sourceStates.filter(s=>s.next!==null&&(source==='All platforms'||s.source===source)).map(s=>s.source):source==='All platforms'?platforms:[source];const pages=Object.fromEntries(sourceStates.filter(s=>s.next!==null).map(s=>[s.source,s.next]));try{const r=await fetch('/api/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({q,sort:append?retrievalSort.current:sort,sources:requested,pages:append?pages:{},youtubeToken:append?nextYoutube:null}),signal:ac.signal});const data=await r.json();if(!r.ok)throw new Error(data.error||'Search unavailable.');if(ac.signal.aborted)return;setCollected(false);setVideos(prev=>[...new Map((append?[...prev,...data.videos]:data.videos).map((v:Video)=>[youtubeId(v.url)||v.url,v])).values()] as Video[]);setSourceStates(prev=>append?[...new Map([...prev,...data.sources].map((s:SourceStatus)=>[s.source,s])).values()]:data.sources);setQuery(q);setInput(q);setNextYoutube(data.nextYoutube);setElapsed((performance.now()-start)/1000);setFetched(data.fetchedAt);if(!append)retrievalSort.current=sort;}catch(e){if(!ac.signal.aborted)setError(e instanceof Error?e.message:'Search failed.')}finally{if(!ac.signal.aborted)setLoading(false)}}
function chooseSource(p:string){setPlatform(p);}
const shown=useMemo(()=>sortVideos(filterVideos(videos,{platform,date,metric:statsOnly}),sort),[videos,platform,sort,date,statsOnly]);
const activeFilters=(date!=='all'?1:0)+(statsOnly!=='all'?1:0)+(platform!=='All platforms'?1:0);
return <div className="app-shell"><header className="topbar"><a className="brand" href="/" aria-label="Vidscope home"><span className="brand-icon"><Play size={19} fill="currentColor"/></span>vidscope<span className="beta">BETA</span></a><div className="header-right"><span className="header-label">VIDEO SEARCH / 01</span><span className="header-label">NO SIGNUP REQUIRED</span></div></header>
<main><section className="search-area"><div className="search-heading"><div><p className="eyebrow">THE VIDEO INDEX</p><h1>Videos across<br/><span>the web.</span></h1></div><p className="intro">One place to explore videos.<br/>Compare the numbers. Go straight to the source.</p></div><form className="searchbox" onSubmit={e=>{e.preventDefault();search()}}><Search size={23}/><input aria-label="Search videos" maxLength={250} value={input} onChange={e=>setInput(e.target.value)} placeholder="Search any topic, creator, or idea…"/>{input&&<button type="button" className="clear" aria-label="Clear search" onClick={()=>setInput('')}><X size={17}/></button>}<button className="search-submit" disabled={loading||!input.trim()}>{loading?<Loader2 className="spin" size={18}/>:<>Search<ArrowRight size={18}/></>}</button></form><div className="suggestions"><span>Explore</span>{['Chocolate chip','Eggless','Decorating','Factory'].map(t=><button key={t} onClick={()=>{setInput(t);search(t+' cookies')}}>{t}<ArrowUpRight size={12}/></button>)}</div></section>
<section className="results"><div className="collection-switch"><button className="connect" onClick={()=>{setPlatform('All platforms');setDate('all');setStatsOnly('all');searchCollection('cookies')}}>Cookie collection · 60 links</button><button className="connect" disabled={loading} onClick={()=>search()}>Search the web<ArrowUpRight size={16}/></button></div>{collected&&<div className="notice"><Info size={17}/><p><strong>Collected cookie videos · 7 platforms.</strong> Two entries have indexed statistic snapshots; other counts are unavailable. Engagement does not establish accuracy. Playback is unverified.</p></div>}<div className="platforms"><button className={platform==='All platforms'?'active':''} onClick={()=>chooseSource('All platforms')}><Layers3 size={17}/>All platforms<span>{videos.length}</span></button>{platforms.map(p=><button key={p} className={platform===p?'active':''} onClick={()=>chooseSource(p)}><b className={'platform-icon '+p.toLowerCase()}>{marks[p]}</b>{p}{videos.some(v=>v.platform===p)&&<span>{videos.filter(v=>v.platform===p).length}</span>}</button>)}</div>
{error&&<div className="error" role="alert">{error}</div>}
{sourceStates.length>0&&<div className="source-statuses" aria-live="polite">{sourceStates.map(s=><div className={'source-status '+s.state} key={s.source}><strong>{s.source}</strong><span>{s.state==='ok'?`${s.count} links this page`:s.state==='not_configured'?'Not connected':'Temporarily unavailable'}</span><small>{s.message}</small>{s.state==='unavailable'&&<button onClick={()=>search(query,false,s.source)}>Retry source</button>}</div>)}</div>}
<div className="result-toolbar"><div><h2>{query?<>Videos for <span>“{query}”</span></>:'Search public videos'}</h2><p aria-live="polite">{shown.length} video links{fetched&&` · ${elapsed.toFixed(2)} seconds`}</p></div><div className="tools"><span className="sort-label">Sort by</span><Picker value={sort} onChange={setSort} items={options} label="Sort videos"/></div></div>
<div className="filter-panel"><div className="filter-caption"><SlidersHorizontal size={17}/>Refine results{activeFilters>0&&<b>{activeFilters}</b>}</div><label>Published<Picker label="Publication date" value={date} onChange={setDate} items={[["all","Any time"],["7","Last 7 days"],["30","Last 30 days"],["365","Last year"]]}/></label><label>Metrics<Picker label="Available metrics" value={statsOnly} onChange={setStatsOnly} items={[["all","Any availability"],["views","Has view count"],["likes","Has like count"],["comments","Has comment count"]]}/></label><button disabled={!activeFilters} onClick={()=>{setDate('all');setStatsOnly('all');chooseSource('All platforms')}}>Reset filters</button></div>
<div className="ranking-note">{collected?'Collection snapshots · Not live counts · Missing metrics stay last.':'Sorted within retrieved results · Missing metrics stay last.'}<span>{shown.length} / {videos.length} videos shown</span></div>
{loading?<div className="video-list" aria-label="Loading videos" role="status">{[1,2,3].map(i=><div className="loading-row" key={i}><Skeleton className="loading-thumb"/><div><Skeleton className="h-6 w-4/5 mb-4"/><Skeleton className="h-4 w-1/2"/></div></div>)}</div>:shown.length?<div className="video-list">{shown.map((v,i)=><article className="video-row" key={v.url}><span className="row-number">{String(i+1).padStart(2,'0')}</span><a className="thumbnail" href={v.url} target="_blank" rel="noopener noreferrer" aria-label={'Watch '+v.title}>{v.thumbnail?<img src={v.thumbnail} alt="" loading={i<3?'eager':'lazy'} onError={e=>{e.currentTarget.style.display='none'}}/>:null}<div className="fallback"><Play size={30}/></div><span className="play-overlay"><Play size={24} fill="white"/></span>{duration(v.duration)&&<span className="duration">{duration(v.duration)}</span>}</a><div className="row-info"><div className="row-source"><span className={'source-label '+v.platform.toLowerCase()}><b>{marks[v.platform]}</b>{v.platform}</span><span>{v.published?new Date(v.published).toLocaleDateString('en',{month:'short',day:'numeric',year:'numeric'}):'Date unavailable'}</span></div><a className="video-title" href={v.url} target="_blank" rel="noopener noreferrer">{v.title}<ArrowUpRight size={20}/></a><p className="creator">{v.creator}</p>{v.metricNote&&<p className="snapshot-note">{v.observedAt} · {v.metricNote}</p>}<button className="details-link" onClick={()=>setSelected(v)}>Video details <Info size={13}/></button></div><div className="row-metrics">{[[Eye,v.views,'Views'],[Heart,v.likes,'Likes'],[MessageCircle,v.comments,'Comments']].map(([Icon,n,label]:any)=><div className={'metric '+(sort.startsWith(label.toLowerCase()+':')?'sorted-metric':'')} key={label} title={n===null?`${label}: unavailable`:`${Number(n).toLocaleString()} ${label}`}><span><Icon size={14}/>{v.platform==='Reddit'&&label==='Comments'?'Post comments':label}</span><strong className={n===null?'unknown':''}>{n===null?'—':`${v.metricNote&&(label==='Views'||label==='Comments')?'≈ ':''}${fmt(n)}`}</strong>{n===null&&<small>Unavailable</small>}</div>)}</div></article>)}</div>:<div className="empty"><Search size={32}/><h3>{query?'No matching videos in this result set':'What do you want to learn?'}</h3><p>{query?'Try another topic or source. Source availability is shown above.':'Enter a topic to search YouTube, Instagram, Facebook, TikTok, Reddit and other sites.'}</p><button className="connect" onClick={()=>{chooseSource('All platforms');setDate('all');setStatsOnly('all')}}>Reset filters</button></div>}
{!loading&&sourceStates.some(s=>s.next!==null&&(platform==='All platforms'||s.source===platform))&&<div className="load-more"><button className="connect" onClick={()=>search(query,true)}>Load more videos<ArrowRight size={16}/></button></div>}
<footer><span><Globe2 size={15}/>More sources. More perspectives.</span><span>{fetched?`Retrieved ${new Date(fetched).toLocaleTimeString()}`:collected?'Collection assembled 8 Sep 2026':'Public video discovery'} · Coverage and metrics vary by source.</span></footer></section></main>
<Dialog open={!!selected} onOpenChange={o=>{if(!o)setSelected(null)}}><DialogContent className="detail-dialog">{selected&&<><DialogTitle>{selected.title}</DialogTitle><DialogDescription>{selected.creator} · {selected.platform}</DialogDescription>{selected.thumbnail&&<img className="detail-image" src={selected.thumbnail} alt="Video thumbnail"/>}<div className="detail-stats">{[['Views',selected.views],['Likes',selected.likes],['Comments',selected.comments]].map(([label,n])=><div key={label}><span>{label}</span><strong>{n===null?'Unavailable':Number(n).toLocaleString()}</strong></div>)}</div><p className="description">{selected.metricNote||'Statistics are supplied where available by the discovery provider.'} {selected.observedAt&&`Observed ${selected.observedAt}.`} {selected.evidenceUrl&&<a href={selected.evidenceUrl} target="_blank" rel="noopener noreferrer">View evidence ↗</a>}</p><p className="description">Discovered via {selected.discovery||selected.platform}. Playback is provided by the original platform.</p><p className="description">{selected.description||'No description supplied by this source.'}</p><a className="search-submit" href={selected.url} target="_blank" rel="noopener noreferrer">Watch on {selected.platform}<ArrowUpRight size={18}/></a></>}</DialogContent></Dialog>
</div>}
